services:
  backend:
    build: ./django_server
    env_file:
      - ./django_server/.env
    volumes:
      - ./django_server/db.sqlite3:/app/db.sqlite3
    networks:
      - app-network
    restart: unless-stopped
  nginx:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - ./dist:/usr/share/nginx/html/
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/logs/:/var/log/nginx/
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
