services:
  mariadb:
    image: mariadb:latest
    container_name: proof_buddy_mariadb
    ports:
      - "3306:3306"
    volumes:
      - mariadb:/var/lib/mysql
      - ./setup.sql:/docker-entrypoint-initdb.d/setup.sql
    env_file:
      - .env
    networks:
      - proof_buddy_network
    restart: unless-stopped

  django_server:
    build:
      context: ./django_server
    container_name: proof_buddy_django_server
    ports:
      - "8000"
    volumes:
      - static:/static
      - logs:/var/log
    env_file:
      - .env
    depends_on:
      - mariadb
    networks:
      - proof_buddy_network
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: proof_buddy_nginx
    ports:
      - "5525:5525"
    volumes:
      - static:/static
      - logs:/var/log/nginx
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - django_server
    networks:
      - proof_buddy_network
    restart: unless-stopped

  client:
    build:
      context: ./client
      args:
        REACT_APP_BACKEND_API_BASE_URL: "http://localhost:5525" # Change this to your backend URL
    container_name: proofbuddy_client
    ports:
      - "9090:80"
    networks:
      - proof_buddy_network
    restart: unless-stopped


networks:
  proof_buddy_network:
    driver: bridge

volumes:
  static:
  logs:
  mariadb: