services:
  mariadb:
    image: mariadb:latest
    container_name: proofbuddy_mariadb
    ports:
      - "3306:3306"
    volumes:
      - mariadb:/var/lib/mysql
      - ./init.sh:/docker-entrypoint-initdb.d/init.sh
    env_file:
      - .env
    networks:
      - proof_buddy_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 30s
      retries: 3
      start_period: 30s
      timeout: 10s
    restart: unless-stopped

  django_server:
    build:
      context: ./django_server
    container_name: proofbuddy_django_server
    ports:
      - "8000:8000"
    volumes:
      - static:/static
      - logs:/var/log
    env_file:
      - .env
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - proof_buddy_network
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: proofbuddy_nginx
    ports:
      - "5525:80"
    volumes:
      - static:/static
      - logs:/var/log/nginx
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      django_server:
        condition: service_started
    networks:
      - proof_buddy_network
    restart: unless-stopped

  client:
    build:
      context: ./client
      args:
        REACT_APP_BACKEND_API_BASE_URL: "http://localhost:5525" # Change this to your backend URL
    container_name: proofbuddy_client
    ports:
      - "9090:80"
    depends_on:
      nginx:
        condition: service_started
    networks:
      - proof_buddy_network
    restart: unless-stopped


networks:
  proof_buddy_network:
    driver: bridge

volumes:
  static:
  logs:
  mariadb: