# Generated by Django 5.0.5 on 2024-11-13 23:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_term_assignment_term'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='instructor',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='students',
        ),
        migrations.RemoveField(
            model_name='term',
            name='lecture',
        ),
        migrations.AddField(
            model_name='term',
            name='instructor',
            field=models.ForeignKey(limit_choices_to={'is_instructor': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='term_instructor', to=settings.AUTH_USER_MODEL),
        ),
    ]
