# Generated by Django 5.0.5 on 2024-11-13 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0004_remove_assignment_instructor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignmentsubmission',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='assignmentsubmission',
            name='updated_at',
        ),
    ]
