# Generated by Django 5.0.5 on 2024-12-01 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0005_remove_assignmentsubmission_created_at_and_more'),
        ('proofs', '0014_alter_proof_definitions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignmentsubmission',
            name='submission',
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='submissions',
            field=models.ManyToManyField(related_name='submissions', to='proofs.proof'),
        ),
    ]
