# Generated by Django 5.0.5 on 2024-12-01 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0006_remove_assignmentsubmission_submission_and_more'),
        ('proofs', '0014_alter_proof_definitions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignmentsubmission',
            name='submissions',
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='proofs',
            field=models.ManyToManyField(related_name='proofs', to='proofs.proof'),
        ),
    ]
