# Generated by Django 5.0.5 on 2026-04-11 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0008_remove_assignment_term_assignmentproof_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='join_code_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='join_code_hash',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
