# Generated by Django 5.0.5 on 2026-04-12 20:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0010_course_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='course',
            name='term',
            field=models.CharField(blank=True, default='Spring 2026', max_length=20, validators=[django.core.validators.RegexValidator(message="Term must be a season followed by a 4-digit year (e.g., 'Fall 2026').", regex='^(Spring|Summer|Fall|Winter) \\d{4}$')]),
        ),
    ]
