# Generated by Django 5.0.5 on 2026-04-13 00:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0011_course_description_course_term'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProofMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_proof_id', models.PositiveIntegerField()),
                ('object_id', models.PositiveIntegerField()),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignments.assignment')),
                ('content_type', models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'equational_reasoning_api'), ('model', 'equationalproof')), models.Q(('app_label', 'induction_api'), ('model', 'inductionproof')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('student', models.ForeignKey(limit_choices_to={'is_instructor': False}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('assignment', 'student', 'template_proof_id', 'content_type')},
            },
        ),
        migrations.DeleteModel(
            name='AssignmentSubmission',
        ),
    ]
