# Generated by Django 5.0.5 on 2026-05-09 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0012_studentproofmapping_delete_assignmentsubmission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignmentproof',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='assignmentproof',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
