# Generated by Django 5.0.5 on 2026-05-16 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0014_courseinvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentproofmapping',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
