# Generated by Django 5.0.5 on 2026-05-16 22:26

from django.db import migrations

def backfill_completed_dates(apps, schema_editor):
    StudentProofMapping = apps.get_model('assignments', 'studentproofmapping')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    
    # 1. Get the concrete ContentType models dynamically from the migration state
    EquationalProof = apps.get_model('equational_reasoning_api', 'equationalproof')
    InductionProof = apps.get_model('induction_api', 'inductionproof')
    
    # 2. Extract the ID numbers for these two specific models
    equational_type = ContentType.objects.get_for_model(EquationalProof)
    induction_type = ContentType.objects.get_for_model(InductionProof)

    # 3. Find all mappings tied to an EquationalProof where is_complete is True
    completed_equational_mappings = StudentProofMapping.objects.filter(
        content_type=equational_type,
        object_id__in=EquationalProof.objects.filter(is_complete=True).values_list('id', flat=True)
    )
    
    # Update them all in bulk to save database operations
    for mapping in completed_equational_mappings:
        mapping.completed_at = mapping.assignment.due_date
        mapping.save()

    # 4. Find all mappings tied to an InductionProof where is_complete is True
    completed_induction_mappings = StudentProofMapping.objects.filter(
        content_type=induction_type,
        object_id__in=InductionProof.objects.filter(is_complete=True).values_list('id', flat=True)
    )
    
    for mapping in completed_induction_mappings:
        mapping.completed_at = mapping.assignment.due_date
        mapping.save()

class Migration(migrations.Migration):

    dependencies = [
        ('equational_reasoning_api', '0007_alter_equationalproof_visible_rules'),
        ('induction_api', '0016_alter_inductionproof_visible_rules'),
        ('assignments', '0015_studentproofmapping_completed_at'),
        ('equational_reasoning_api', '0008_equationalproof_support_rewrite_complexity'),
        ('induction_api', '0017_inductionproof_support_rewrite_complexity'),
    ]

    operations = [
        migrations.RunPython(backfill_completed_dates),
    ]
