# Generated by Django 5.0.5 on 2026-05-30 20:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0016_auto_20260516_1826'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentShareRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sender', models.ForeignKey(limit_choices_to={'is_instructor': True}, on_delete=django.db.models.deletion.CASCADE, related_name='sent_assignment_shares', to=settings.AUTH_USER_MODEL)),
                ('source_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_shares_history', to='assignments.course')),
                ('staged_assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='share_request', to='assignments.assignment')),
                ('target_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_assignment_shares', to='assignments.course')),
            ],
            options={
                'unique_together': {('source_course', 'target_course', 'staged_assignment')},
            },
        ),
    ]
