# Generated by Django 5.0.5 on 2026-05-30 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0017_assignmentsharerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentproof',
            name='original_proof_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
