# Generated by Django 5.0.5 on 2025-12-21 00:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InductionProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('tag', models.CharField(blank=True, max_length=100, null=True)),
                ('proof_type', models.CharField(choices=[('induction_int', 'Integer Induction'), ('induction_lists', 'List Induction')], default='induction_int', max_length=50)),
                ('induction_type', models.CharField(choices=[('integers', 'Integers'), ('lists', 'Lists')], default='integers', max_length=20)),
                ('induction_variable', models.CharField(max_length=100)),
                ('anchor_value', models.IntegerField()),
                ('leap_variable', models.CharField(max_length=100)),
                ('lhs_leap_goal', models.TextField(blank=True, null=True)),
                ('rhs_leap_goal', models.TextField(blank=True, null=True)),
                ('lhs_anchor_goal', models.TextField(blank=True, null=True)),
                ('rhs_anchor_goal', models.TextField(blank=True, null=True)),
                ('inductive_hypothesis_lhs', models.TextField(blank=True, default='')),
                ('inductive_hypothesis_rhs', models.TextField(blank=True, default='')),
                ('current_side', models.CharField(choices=[('LHS', 'Left Hand Side'), ('RHS', 'Right Hand Side')], default='LHS', max_length=3)),
                ('current_goal', models.TextField(blank=True, null=True)),
                ('is_anchor_case', models.BooleanField(default=False)),
                ('is_valid', models.BooleanField(default=True)),
                ('definition', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='induction_proofs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='induction_a_user_id_83f304_idx'), models.Index(fields=['proof_type'], name='induction_a_proof_t_efd34f_idx'), models.Index(fields=['induction_type'], name='induction_a_inducti_801683_idx')],
            },
        ),
    ]
