# Generated by Django 5.0.5 on 2025-12-21 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('induction_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InductionProofLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case', models.CharField(choices=[('base', 'Base Case'), ('leap', 'Leap Case')], max_length=10)),
                ('side', models.CharField(choices=[('LHS', 'Left Hand Side'), ('RHS', 'Right Hand Side')], max_length=3)),
                ('racket', models.TextField()),
                ('rule', models.CharField(blank=True, default='', max_length=255)),
                ('start_position', models.IntegerField(default=0)),
                ('line_number', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('proof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proof_lines', to='induction_api.inductionproof')),
            ],
            options={
                'ordering': ['case', 'side', 'line_number'],
                'indexes': [models.Index(fields=['proof', 'case', 'side', 'line_number'], name='induction_a_proof_i_6c3588_idx')],
            },
        ),
    ]
