# Generated by Django 5.0.5 on 2025-12-26 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('induction_api', '0002_inductionproofline'),
    ]

    operations = [
        migrations.AddField(
            model_name='inductionproofline',
            name='substitution',
            field=models.TextField(blank=True, default=''),
        ),
    ]
