# Generated by Django 5.0.5 on 2025-12-26 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('induction_api', '0003_inductionproofline_substitution'),
    ]

    operations = [
        migrations.AddField(
            model_name='inductionproofline',
            name='selected_node',
            field=models.IntegerField(default=0),
        ),
    ]
