# Generated by Django 5.0.5 on 2025-12-31 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('induction_api', '0006_inductionproofline_result_node'),
    ]

    operations = [
        migrations.AddField(
            model_name='inductionproofline',
            name='json_tree',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
