# Generated by Django 5.0.5 on 2025-12-31 08:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('induction_api', '0007_inductionproofline_json_tree'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inductionproof',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddConstraint(
            model_name='inductionproof',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('user', 'name', 'tag'), name='unique_active_induction_proof_per_user'),
        ),
    ]
