# Generated by Django 5.0.5 on 2025-12-31 08:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('induction_api', '0008_inductionproof_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='inductionproof',
            name='unique_active_induction_proof_per_user',
        ),
        migrations.AddIndex(
            model_name='inductionproof',
            index=models.Index(fields=['user', 'name', 'tag', 'is_active'], name='induction_a_user_id_d94689_idx'),
        ),
    ]
