# Generated by Django 5.0.5 on 2026-01-31 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('induction_api', '0009_remove_inductionproof_unique_active_induction_proof_per_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inductionproof',
            name='anchor_value',
            field=models.CharField(max_length=100),
        ),
    ]
