# Generated by Django 5.0.5 on 2026-02-21 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('induction_api', '0010_alter_inductionproof_anchor_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='inductionproofline',
            name='errors',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='inductionproofline',
            name='hide_expression',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inductionproofline',
            name='hide_justification',
            field=models.BooleanField(default=False),
        ),
    ]
