# Generated by Django 5.0.5 on 2026-03-28 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('induction_api', '0011_inductionproofline_errors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inductionproof',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
