# Generated by Django 5.0.5 on 2026-04-14 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('induction_api', '0012_inductionproof_is_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='inductionproof',
            name='support_current_lhs_rhs',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='inductionproof',
            name='support_errors',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='inductionproof',
            name='support_ih',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='inductionproof',
            name='support_premise',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='inductionproof',
            name='support_rule_set',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='inductionproof',
            name='support_value_mapping',
            field=models.BooleanField(default=True),
        ),
    ]
