# Generated by Django 5.0.5 on 2026-04-26 00:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('induction_api', '0013_inductionproof_support_current_lhs_rhs_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='inductionproof',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='induction_proofs', to=settings.AUTH_USER_MODEL),
        ),
    ]
