# Generated by Django 5.0.5 on 2026-04-26 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('induction_api', '0014_alter_inductionproof_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='inductionproof',
            name='visible_rules',
            field=models.TextField(blank=True, default=list),
        ),
    ]
