# Generated by Django 5.0.5 on 2026-04-26 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('induction_api', '0015_inductionproof_visible_rules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inductionproof',
            name='visible_rules',
            field=models.TextField(blank=True, default=dict),
        ),
    ]
