# Generated by Django 5.0.5 on 2026-05-17 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('induction_api', '0016_alter_inductionproof_visible_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='inductionproof',
            name='support_rewrite_complexity',
            field=models.BooleanField(default=True),
        ),
    ]
