# Generated by Django 5.0.5 on 2026-05-16 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('induction_api', '0016_alter_inductionproof_visible_rules'),
    ]

    operations = [
        migrations.CreateModel(
            name='InductionProofLineComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(max_length=3)),
                ('line_number', models.IntegerField()),
                ('role', models.CharField(choices=[('student', 'Student'), ('instructor', 'Instructor')], max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='induction_api.inductionproof')),
            ],
        ),
    ]
