# Generated by Django 5.0.5 on 2026-05-23 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('induction_api', '0017_inductionproof_support_rewrite_complexity'),
        ('induction_api', '0017_inductionprooflinecomment'),
    ]

    operations = [
    ]
