# Generated by Django 5.0.5 on 2024-05-07 22:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Definition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tag', models.CharField(max_length=100)),
                ('def_type', models.CharField(max_length=100)),
                ('expression', models.CharField(max_length=255)),
                ('notes', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='definitions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Proof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tag', models.CharField(max_length=100)),
                ('lsh', models.CharField(max_length=100)),
                ('rsh', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('isComplete', models.BooleanField(default=False)),
                ('template', models.CharField(choices=[('ER', 'ER'), ('MP', 'MP'), ('MT', 'MT'), ('DS', 'DS'), ('ADD', 'ADD')], default='ER', max_length=3)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proofs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProofLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_side', models.BooleanField(default=True)),
                ('racket', models.CharField(max_length=255)),
                ('rule', models.CharField(max_length=100)),
                ('start_position', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('errors', models.TextField(default='')),
                ('proof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proof_lines', to='proofs.proof')),
            ],
        ),
    ]
