# Generated by Django 5.0.5 on 2024-05-07 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proofs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='definition',
            name='proof',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='definitions', to='proofs.proof'),
        ),
    ]
