# Generated by Django 5.0.5 on 2024-05-07 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proofs', '0002_definition_proof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proof',
            name='lsh',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='proof',
            name='rsh',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
