# Generated by Django 5.0.5 on 2024-05-08 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proofs', '0005_alter_proof_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='definition',
            old_name='name',
            new_name='label',
        ),
        migrations.RemoveField(
            model_name='definition',
            name='tag',
        ),
    ]
