# Generated by Django 5.0.5 on 2024-05-08 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proofs', '0006_rename_name_definition_label_remove_definition_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='definition',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
