# Generated by Django 5.0.5 on 2024-05-14 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proofs', '0007_alter_definition_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='proofline',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
