# Generated by Django 5.0.5 on 2024-05-18 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proofs', '0008_proofline_deleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proof',
            old_name='lsh',
            new_name='lhs',
        ),
        migrations.RenameField(
            model_name='proof',
            old_name='rsh',
            new_name='rhs',
        ),
    ]
