# Generated by Django 5.0.5 on 2024-08-22 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proofs', '0009_rename_lsh_proof_lhs_rename_rsh_proof_rhs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='definition',
            name='expression',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
