# Generated by Django 5.0.5 on 2024-06-05 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proofs', '0009_rename_lsh_proof_lhs_rename_rsh_proof_rhs'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='proof',
            unique_together={('name', 'tag')},
        ),
    ]
