# Generated by Django 5.0.5 on 2024-06-05 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proofs', '0010_alter_proof_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='proof',
            unique_together=set(),
        ),
    ]
