# Generated by Django 5.0.5 on 2024-10-19 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proofs', '0010_alter_definition_expression'),
        ('proofs', '0011_alter_proof_unique_together'),
    ]

    operations = [
    ]
