# Generated by Django 5.0.5 on 2024-10-19 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proofs', '0012_merge_20241018_2037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='definition',
            name='proof',
        ),
        migrations.AddField(
            model_name='proof',
            name='definitions',
            field=models.ManyToManyField(related_name='proof_definitions', to='proofs.definition'),
        ),
    ]
