# Generated by Django 5.0.5 on 2024-10-19 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proofs', '0013_remove_definition_proof_proof_definitions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proof',
            name='definitions',
            field=models.ManyToManyField(blank=True, related_name='proof_definitions', to='proofs.definition'),
        ),
    ]
