# Generated by Django 5.0.5 on 2025-07-24 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proofs', '0014_alter_proof_definitions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proofline',
            name='start_position',
            field=models.SmallIntegerField(),
        ),
    ]
