# Generated by Django 5.0.5 on 2025-07-21 18:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proofs', '0014_alter_proof_definitions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='proofline',
            name='start_position',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='definition',
            unique_together={('label', 'created_by')},
        ),
    ]
