# Generated by Django 5.0.5 on 2025-07-25 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proofs', '0015_alter_definition_unique_together'),
        ('proofs', '0015_alter_proofline_start_position'),
        ('proofs', '0015_alter_proofline_start_position_and_more'),
    ]

    operations = [
    ]
