# Generated by Django 5.0.5 on 2025-08-06 18:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proofs', '0016_merge_20250806_1418'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Generic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('assumption', models.CharField(blank=True, default='', max_length=100)),
                ('never_null', models.BooleanField(blank=True, default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('label', 'created_by')},
            },
        ),
        migrations.AddField(
            model_name='proof',
            name='generics',
            field=models.ManyToManyField(blank=True, related_name='proofs', to='proofs.generic'),
        ),
    ]
