# Generated by Django 5.0.5 on 2025-08-15 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proofs', '0016_merge_20250725_0934'),
        ('proofs', '0017_generic_proof_generics'),
    ]

    operations = [
    ]
