# Generated by Django 5.0.5 on 2025-08-15 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proofs', '0018_merge_20250815_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generic',
            name='assumption',
        ),
        migrations.RemoveField(
            model_name='generic',
            name='never_null',
        ),
        migrations.AddField(
            model_name='generic',
            name='restrictions',
            field=models.CharField(default='None', max_length=127),
        ),
    ]
