# Generated by Django 5.0.5 on 2026-05-17 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proofs', '0020_prooflinecomment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProofLineComment',
        ),
    ]
