# Generated by Django 5.0.5 on 2026-05-24 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proofs', '0021_delete_prooflinecomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='definition',
            name='expression_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
