import React, { useState, useEffect } from "react";
import Modal from "react-bootstrap/Modal";
import Button from "react-bootstrap/Button";
import ButtonGroup from "react-bootstrap/ButtonGroup";
import Tooltip from "react-bootstrap/Tooltip";
import OverlayTrigger from "react-bootstrap/OverlayTrigger";

const PARAM_ROWS = [
  { key: "support_errors",          label: "Error Messages" },
  { key: "support_current_lhs_rhs", label: "Current LHS/RHS" },
  { key: "support_ih",              label: "Induction Hypothesis" },
  { key: "support_premise",         label: "Premise" },
  { key: "support_rule_set",        label: "Rule Set" },
  { key: "support_value_mapping",   label: "Value Mapping" }
];

const DEFAULT_PARAMS = {
  support_errors: true,
  support_current_lhs_rhs: true,
  support_ih: true,
  support_premise: true,
  support_rule_set: true,
  support_value_mapping: true
};

const TOOLTIPSLOW = {
  support_errors: "generic error notification",
  support_current_lhs_rhs: "fields not displayed",
  support_ih: "field manually entered, only accessible via Utils",
  support_premise: "field manually entered",
  support_rule_set: "complete ruleset displayed",
  support_value_mapping: "user enters parameter -> value mappings when applying rules"
}

const TOOLTIPSHIGH = {
  support_errors: "targeted error/hint messages",
  support_current_lhs_rhs: "fields persistently visible",
  support_ih: "field autogenerated, persistently visible",
  support_premise: "field autogenerated",
  support_rule_set: "instructor customized ruleset displayed",
  support_value_mapping: "parameter -> value autogenerated when applying rules"
}

export default function SetParametersModal({ show, onHide, params, onSave }) {
  const [local, setLocal] = useState(DEFAULT_PARAMS);

  // Sync local state whenever modal opens or params change
  useEffect(() => {
    if (show) {
      setLocal({ ...DEFAULT_PARAMS, ...params });
    }
  }, [show, params]);

  const allHigh = PARAM_ROWS.every(r => local[r.key] === true);
  const allLow  = PARAM_ROWS.every(r => local[r.key] === false);

  const setAll = (value) => {
    const next = {};
    PARAM_ROWS.forEach(r => { next[r.key] = value; });
    setLocal(next);
  };

  const toggle = (key, value) => {
    setLocal(prev => ({ ...prev, [key]: value }));
  };

  const handleSave = () => {
    onSave(local);
    onHide();
  };

  return (
    <Modal show={show} onHide={onHide} centered>
      <Modal.Header closeButton>
        <Modal.Title>Set Parameters</Modal.Title>
      </Modal.Header>

      <Modal.Body>
        <table style={{ width: "100%", borderCollapse: "separate", borderSpacing: "0 6px" }}>
          <thead>
            <tr>
              <th style={{ paddingBottom: "4px" }}>Parameter</th>
              <th style={{ textAlign: "center", paddingBottom: "4px" }}>Low Support</th>
              <th style={{ textAlign: "center", paddingBottom: "4px" }}>High Support</th>
            </tr>
          </thead>
          <tbody>
            {/* ALL row */}
            <tr style={{ borderBottom: "1px solid #dee2e6" }}>
              <td style={{ paddingBottom: "8px", fontWeight: "600" }}>ALL</td>
              <td style={{ textAlign: "center", paddingBottom: "8px" }}>
                <OverlayTrigger
                    placement="right"
                    overlay={
                      <Tooltip>
                        all components toggled to Low, can still be set individually
                      </Tooltip>
                    }
                  >
                    <Button
                      size="sm"
                      variant={allLow ? "primary" : "outline-secondary"}
                      onClick={() => setAll(false)}
                    >
                      Low
                    </Button>
                  </OverlayTrigger>
              </td>
              <td style={{ textAlign: "center", paddingBottom: "8px" }}>
                <OverlayTrigger
                    placement="right"
                    overlay={
                      <Tooltip>
                        all components toggled to High, can still be set individually
                      </Tooltip>
                    }
                  >
                    <Button
                      size="sm"
                      variant={allHigh ? "primary" : "outline-secondary"}
                      onClick={() => setAll(true)}
                    >
                      High
                    </Button>
                  </OverlayTrigger>
              </td>
            </tr>

            {/* Individual rows */}
            {PARAM_ROWS.map(({ key, label }) => (
              <tr key={key}>
                <td style={{ paddingTop: "4px" }}>{label}</td>
                <td style={{ textAlign: "center", paddingTop: "4px" }}>
                  <OverlayTrigger
                    placement="right"
                    overlay={
                      <Tooltip id={'tooltip-${key}'}>
                        {TOOLTIPSLOW[key]}
                      </Tooltip>
                    }
                  >
                    <Button
                    size="sm"
                    variant={local[key] === false ? "primary" : "outline-secondary"}
                    onClick={() => toggle(key, false)}
                  >
                    Low
                    </Button>
                  </OverlayTrigger>
                </td>
                <td style={{ textAlign: "center", paddingTop: "4px" }}>
                  <OverlayTrigger
                    placement="right"
                    overlay={
                      <Tooltip id={'tooltip-${key}'}>
                        {TOOLTIPSHIGH[key]}
                      </Tooltip>
                    }
                  >
                    <Button
                    size="sm"
                    variant={local[key] === true ? "primary" : "outline-secondary"}
                    onClick={() => toggle(key, true)}
                  >
                    High
                    </Button>
                  </OverlayTrigger>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </Modal.Body>

      <Modal.Footer>
        <Button variant="secondary" onClick={onHide}>Cancel</Button>
        <Button variant="primary" onClick={handleSave}>Save</Button>
      </Modal.Footer>
    </Modal>
  );
}
