# Generated by Django 5.0.5 on 2026-01-03 01:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EquationalProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('tag', models.CharField(blank=True, max_length=100, null=True)),
                ('lhs_goal', models.TextField()),
                ('rhs_goal', models.TextField()),
                ('current_side', models.CharField(choices=[('LHS', 'Left Hand Side'), ('RHS', 'Right Hand Side')], default='LHS', max_length=3)),
                ('is_valid', models.BooleanField(default=True)),
                ('is_complete', models.BooleanField(default=False)),
                ('definition', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equational_proofs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EquationalProofLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('LHS', 'Left Hand Side'), ('RHS', 'Right Hand Side')], max_length=3)),
                ('racket', models.TextField()),
                ('json_tree', models.JSONField(blank=True, default=dict)),
                ('rule', models.CharField(blank=True, default='', max_length=255)),
                ('substitution', models.TextField(blank=True, default='')),
                ('start_position', models.IntegerField(default=0)),
                ('selected_node', models.IntegerField(default=0)),
                ('result_node', models.IntegerField(default=0)),
                ('line_number', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('proof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proof_lines', to='equational_reasoning_api.equationalproof')),
            ],
            options={
                'ordering': ['side', 'line_number'],
            },
        ),
        migrations.AddIndex(
            model_name='equationalproof',
            index=models.Index(fields=['user', '-created_at'], name='equational__user_id_d3b9a6_idx'),
        ),
        migrations.AddIndex(
            model_name='equationalproof',
            index=models.Index(fields=['user', 'name', 'tag', 'is_active'], name='equational__user_id_80da76_idx'),
        ),
        migrations.AddIndex(
            model_name='equationalproofline',
            index=models.Index(fields=['proof', 'side', 'line_number'], name='equational__proof_i_7e5ef3_idx'),
        ),
        migrations.AddConstraint(
            model_name='equationalproofline',
            constraint=models.UniqueConstraint(fields=('proof', 'side', 'line_number'), name='unique_equational_proof_line'),
        ),
    ]
