# Generated by Django 5.0.5 on 2026-01-25 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equational_reasoning_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equationalproofline',
            name='hide_expression',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='equationalproofline',
            name='hide_justification',
            field=models.BooleanField(default=False),
        ),
    ]
