# Generated by Django 5.0.5 on 2026-02-01 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equational_reasoning_api', '0002_equationalproofline_hide_expression_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equationalproofline',
            name='errors',
            field=models.TextField(blank=True, default=''),
        ),
    ]
