# Generated by Django 5.0.5 on 2026-04-12 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equational_reasoning_api', '0003_equationalproofline_errors'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='equationalproof',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equational_proofs', to=settings.AUTH_USER_MODEL),
        ),
    ]
