# Generated by Django 5.0.5 on 2026-04-14 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equational_reasoning_api', '0004_alter_equationalproof_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='equationalproof',
            name='support_current_lhs_rhs',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='equationalproof',
            name='support_errors',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='equationalproof',
            name='support_ih',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='equationalproof',
            name='support_premise',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='equationalproof',
            name='support_rule_set',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='equationalproof',
            name='support_value_mapping',
            field=models.BooleanField(default=True),
        ),
    ]
