# Generated by Django 5.0.5 on 2026-04-26 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equational_reasoning_api', '0005_equationalproof_support_current_lhs_rhs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equationalproof',
            name='visible_rules',
            field=models.TextField(blank=True, default=list),
        ),
    ]
