# Generated by Django 5.0.5 on 2026-04-26 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equational_reasoning_api', '0006_equationalproof_visible_rules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equationalproof',
            name='visible_rules',
            field=models.TextField(blank=True, default=dict),
        ),
    ]
