# Generated by Django 5.0.5 on 2026-05-17 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equational_reasoning_api', '0007_alter_equationalproof_visible_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='equationalproof',
            name='support_rewrite_complexity',
            field=models.BooleanField(default=True),
        ),
    ]
