# Generated by Django 5.0.5 on 2026-05-23 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equational_reasoning_api', '0008_equationalproof_support_rewrite_complexity'),
        ('equational_reasoning_api', '0008_equationalprooflinecomment'),
    ]

    operations = [
    ]
