# Generated by Django 5.0.5 on 2026-05-30 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equational_reasoning_api', '0009_merge_20260523_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equationalprooflinecomment',
            name='proof',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proof_comments', to='equational_reasoning_api.equationalproof'),
        ),
    ]
